# ArchCheck -> Plugin for checking players
# GitHub: https://github.com/ArchDevs
# Discord: archdevx
# dev: ArchDev

teleport-player-on-check: true
tp-player-on-check-pos:
  world: "world"
  x: 100
  y: 100
  z: 100

bossbar:
  title: "&cCheck"
  color: RED

messages:
  # General messages
  player-not-found: "&cPlayer not found"
  no-arguments: "&cPlease provide some arguments to command"
  config-reload: "&aConfig has been reloaded"
  
  # Messages on/while/before check
  already-on-check: "&cPlayer is already on check"
  not-on-check: "&cPlayer is not on check"
  
  already-checking: "&cYou are already checking player"
  
  player-used-command: "&fPlayer tried to use command"
  no-commands-on-check: "&cYou can't use commands while on check!"