# ArchCheck -> Plugin for checking players
# GitHub: https://github.com/Damgel0
# Discord: archonixs
# dev: ArchDev

bossbar:
  title: "&cCheck"
  color: RED

messages:
  # General messages
  player-not-found: "&cPlayer not found"
  
  # Messages on/while/before check
  already-on-check: "&cPlayer is already on check"
  not-on-check: "&cPlayer is not on check"
  
  checker-already-checking: "&cYou are already checking player"
  checker-not-found: "&cChecker is not online"
  
  player-used-command: "&fPlayer tried to use command"
  no-command-on-check: "&cYou can't use commands while on check!"